### Get all ciders
GET http://localhost:8080/api/ciders

### Get a cider by ID
@cider_id = 101
GET http://localhost:8080/api/ciders/{{cider_id}}


### Create a new cider
POST http://localhost:8080/api/ciders
Content-Type: application/json
Authorization: Basic user1 user1

{
  "nazwa": "aaaddsadsasdadssadsadaddNew Cidear",
  "styl": "Półsłodki",
  "cena": 25.0
}

### Get all producers
GET http://localhost:8080/api/producers

### Get a producer by ID
@producer_id = 1
GET http://localhost:8080/api/producers/{{producer_id}}

### Create a new producer
POST http://localhost:8080/api/producers
Content-Type: application/json

{
  "id": 10,
  "nazwa": "jan",
  "opis": "najlepszy cydr w tym wszechswiecie"
}
